GCP:
  PROJECT: hmh-em-deepasm
  REGION: us-east1
  BUCKET: hmh_deepasm
  MODEL_FOLDER: models
  BQ_DATASET_EXPIRATION_SEC: 864000 # 10 days
  CLOUDASM_DATASET: cloudasm_encode_2019
  SAMPLES_DATASET: samples

GENOMICS:
  REFERENCE_GENOME: hg19
  GENOMIC_LENGTH: 250
  ENCODE_BLACKLIST_REGIONS_URL: https://www.encodeproject.org/files/ENCFF001TDO/@@download/ENCFF001TDO.bed.gz
  NB_NUCLEOTIDES_PER_CLUSTER: 800000
  MIN_NB_CPG_PER_REGION_IN_REF_GENOME: 2
  MIN_NB_READS_IN_SEQUENCE: 20
  NB_CPG_FOR_PADDING: 10
  SORT_READS_RANDOMLY: False
  MIN_FRACTION_OF_NB_CPG_IN_READ: 0.8

ASM:
  MIN_NB_CPG_FOR_ASM: 3
  MAX_CPG_COV: 200
  MIN_CPG_COV: 10
  MAX_P_VALUE: 0.05
  MAX_BH_THRESHOLD: 0.05
  MIN_ASM_REGION_EFFECT: 0.2
  MIN_NB_CPG_SAME_DIRECTION: 3
  MIN_NB_CONSECUTIVE_CPG_SAME_DIRECTION: 2


FEATURE_PREP:
  KERNEL_FM_NB_VALUES: 10
  KERNEL_FM_BANDWIDTH: 0.1
  KERNEL_COV_NB_MAX: 200
  KERNEL_COV_NB_STEP: 10
  KERNEL_COV_BANDWIDTH: 5
  KERNEL_TYPE: gaussian

HMM:
  N_STATES: 5
  COVARIANCE: tied
  N_ITERATIONS: 200
  ALGORITHM: viterbi
  VAR_NAME: directional_cpg_frac


SAMPLES:
  TRAINING:
    - gm12878
    - CD14
    - fibroblast
    - A549
    - spleen_female_adult
    - HeLa_S3
  VALIDATION:
    - mammary_epithelial
    - sk_n_sh
    - CD34
  TESTING:
    - HepG2
    - right_lobe_liver
    - t_cell_male_adult


VARS_TO_REMOVE:
  - read_fm
  - cpg_pos
  - cpg_cov
  - cpg_dist
  - genomic_picture
  - global_cpg_fm
  - tot_nb_reads
  - tot_nb_cpg
  - cpg_cov_kd
  - read_fm_kd
  - cpg_fm_kd
  - cpg_dist_kd

VARS_TO_KEEP:
  sample: STRING
  chr: INTEGER
  asm_snp: INTEGER
  region_inf: INTEGER
  region_sup: INTEGER

VARS_TO_NORMALIZE:
  - region_nb_cpg
  - nb_cpg_found
  - nb_reads
  - encode_ChiP_V2
  - tf_motifs
  - cpg_cov_kd
  - read_fm_kd
  - cpg_fm_kd
  - cpg_dist_kd
  - std_read_fm
  - mean_read_fm
  - std_cpg_fm
  - mean_cpg_fm
  - std_cpg_cov
  - mean_cpg_cov
  - std_cpg_dist
  - mean_cpg_dist

CATEGORICAL_VARS:
  - chr
  - sample_category
  - dnase

CAT_VARS_OHE:
  - chr
