GCP:
  PROJECT: hmh-em-deepasm
  REGION: us-east1
  BUCKET: hmh_deepasm
  ARTIFACT_REGISTRY_REPO: docker-repo
  BQ_DATASET_EXPIRATION_SEC: 864000 # 10 days
  CLOUDASM_DATASET: cloudasm_encode_2019

GENOMICS:
  REFERENCE_GENOME: hg19
  GENOMIC_LENGTH: 250
  ENCODE_BLACKLIST_REGIONS_URL: https://www.encodeproject.org/files/ENCFF001TDO/@@download/ENCFF001TDO.bed.gz
  NB_NUCLEOTIDES_PER_CLUSTER: 800000
  MIN_NB_CPG_PER_REGION_IN_REF_GENOME: 2
  MIN_NB_READS_IN_SEQUENCE: 20
  KEEP_ONLY_EXTREME_READS: False
  NB_CPG_FOR_PADDING: 10
  SORT_READS_RANDOMLY: False
  MIN_FRACTION_OF_NB_CPG_IN_READ: 0.75

ASM:
  MIN_NB_CPG_FOR_ASM: 3
  MAX_CPG_COV: 200
  MIN_CPG_COV: 10
  MAX_P_VALUE: 0.05
  MAX_BH_THRESHOLD: 0.05
  MIN_ASM_REGION_EFFECT: 0.2
  MIN_NB_CPG_SAME_DIRECTION: 3
  MIN_NB_CONSECUTIVE_CPG_SAME_DIRECTION: 2


FEATURE_PREP:
  KERNEL_FM_NB_VALUES: 10
  KERNEL_FM_BANDWIDTH: 0.1
  KERNEL_COV_NB_MAX: 200
  KERNEL_COV_NB_STEP: 10
  KERNEL_COV_BANDWIDTH: 5
  KERNEL_TYPE: gaussian

HMM:
  N_STATES: 5
  MODEL_TYPE: Variational Gaussian
  COVARIANCE: tied
  N_ITERATIONS: 100
  ALGORITHM: viterbi
  VAR_NAME: cpg_directional_fm
  MODEL_NAME: hmm_model_2af650b_8states

ML:
  ML_MODE: TESTING # TESTING OR PRODUCTION
  NB_DATA_POINTS_TESTING: 100000
  TESTING:
    HMM_N_MODEL_LOOP: 2
    LABEL_NAME: asm_not_corrected
    BATCH_SIZE: 1024
    PADDING_VALUE: 0
    DROPOUT_RATE: 0.5
    N_EPOCHS: 20
    N_RANDOM_SEARCH_TREE: 3
    N_RANDOM_SEARCH_1D: 3
  PRODUCTION:
    HMM_N_MODEL_LOOP: 10
    LABEL_NAME: asm_not_corrected
    BATCH_SIZE: 1024
    PADDING_VALUE: 0
    DROPOUT_RATE: 0.5
    N_EPOCHS: 100
    N_RANDOM_SEARCH_TREE: 50
    N_RANDOM_SEARCH_1D: 15


SAMPLES:
  TRAINING:
    - gm12878
    - CD14
    - fibroblast
    - A549
    - spleen_female_adult
    - HeLa_S3
  VALIDATION:
    - mammary_epithelial
    - sk_n_sh
    - CD34
  TESTING:
    - HepG2
    - right_lobe_liver
    - t_cell_male_adult


VARS_TO_REMOVE:
  - read_fm
  - cpg_fm
  - cpg_pos
  - cpg_cov
  - cpg_dist
  - genomic_picture
  - global_cpg_fm
  - tot_nb_reads
  - tot_nb_cpg
  - cpg_cov_kd
  - read_fm_kd
  - cpg_fm_kd
  - cpg_dist_kd

VARS_TO_KEEP:
  sample: STRING
  chr: INTEGER
  asm_snp: INTEGER
  region_inf: INTEGER
  region_sup: INTEGER


CAT_VARS_OHE:
  - chr
