# To execute
#gcloud run jobs deploy --region=us-east1 --project=hmh-em-deepasm process_json.yaml

apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: process-json
  labels:
    cloud.googleapis.com/location: us-east1
spec:
  template:
    spec:
      taskCount: 2
      template:
        spec:
          containers:
          - image: us-east1-docker.pkg.dev/hmh-em-deepasm/docker-repo/process-raw-json:latest
            env:
            - name: BUCKET_NAME
              value: hmh_deepasm
            - name: FILE_PATH
              value: bq_tables/250bp_asm_labelled/raw-000000000000.json
            resources:
              limits:
                cpu: '4'
                memory: 16Gi
          maxRetries: 2
          timeoutSeconds: '600'