GCP:
  PROJECT_ID: hmh-em-deepasm
  REGION: us-east1
  IMAGE: us-east1-docker.pkg.dev/hmh-em-deepasm/docker-repo/python
  BUCKET_NAME: hmh_deepasm

GENOMICS:
  GENOMIC_LENGTH: 250
  MIN_NB_READS_IN_SEQUENCE: 10
  SORT_READS_RANDOMLY: False
  MIN_FRACTION_OF_NB_CPG_IN_READ: 0.8
  REFERENCE_GENOME: hg19

FEATURE_PREP:
  KERNEL_FM_NB_VALUES: 10
  KERNEL_FM_BANDWIDTH: 0.1
  KERNEL_COV_NB_MAX: 200
  KERNEL_COV_NB_STEP: 10
  KERNEL_COV_BANDWIDTH: 5
  KERNEL_TYPE: gaussian

VARS_TO_REMOVE:
  - read_fm
  - cpg_pos
  - cpg_cov
  - cpg_dist
  - genomic_picture
  - global_cpg_fm
  - tot_nb_reads
  - tot_nb_cpg
  - cpg_cov_kd
  - read_fm_kd
  - cpg_fm_kd
  - cpg_dist_kd

VARS_TO_KEEP:
  sample: STRING
  chr: INTEGER
  asm_snp: INTEGER
  region_inf: INTEGER
  region_sup: INTEGER

VARS_TO_NORMALIZE:
  - region_nb_cpg
  - nb_cpg_found
  - nb_reads
  - encode_ChiP_V2
  - tf_motifs
  - cpg_cov_kd
  - read_fm_kd
  - cpg_fm_kd
  - cpg_dist_kd
  - std_read_fm
  - mean_read_fm
  - std_cpg_fm
  - mean_cpg_fm
  - std_cpg_cov
  - mean_cpg_cov
  - std_cpg_dist
  - mean_cpg_dist

CATEGORICAL_VARS:
  - chr
  - sample_category
  - dnase

CAT_VARS_OHE:
  - chr
